repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --check
        language: system
        types: [file, python]
        files: "^(src|test)/"
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        language: system
        types: [file, python]
        files: "^(src|test)/"
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: system
        types: [file, python]
        files: "^(src|test)/"
