name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install

      - name: Lint with Ruff
        run: |
          poetry run ruff --version
          poetry run ruff check .

      - name: Format Check with Black
        run: |
          poetry run black --check .

      - name: Type Check with Pyright
        run: |
          poetry run pyright

      - name: Run Tests
        run: |
          poetry run pytest --maxfail=1 --disable-warnings
